services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dev
    ports:
      - '15432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - shared-network

networks:
  shared-network:
    external: true

# docker network create shared-network