# 1. Next.js build
FROM node:22-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm@10.4.1

COPY package.json ./
RUN pnpm install

COPY . .
RUN pnpm build || (echo "Build failed" && exit 1)


# 2. Runtime environment (keep only minimal files)
FROM node:22-alpine AS runtime
RUN apk update && apk add curl

WORKDIR /app

# Copy only the Next.js standalone output (node_modules not required)
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Remove unnecessary cache
RUN rm -rf .next/cache

# Expose port
EXPOSE 3000

# Run Next.js server
CMD ["node", "server.js"]