# docker network create app-network

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dev
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app_network

  app-green:
    # image: web
    build:
      dockerfile: apps/web/Dockerfile
      context: .
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - apps/web/.env.local
    networks:
      - app-network

networks:
  app-network:
    external: true
