x-shared: &common-service
  image: node:20-alpine
  working_dir: /app
  volumes:
    - .:/app
    - /app/node_modules
  environment:
    - TZ=Asia/Seoul

  # networks:
  #   - app-network

services:
  #   worker:
  #     build:
  #       context: .
  #       dockerfile: /app/apps/worker/Dockerfile
  #     container_name: worker
  #     # environment:
  #     #   R2_ENDPOINT: https://your-r2-id.r2.cloudflarestorage.com
  #     #   R2_ACCESS_KEY_ID: your-access-key
  #     #   R2_SECRET_ACCESS_KEY: your-secret-key
  #     #   R2_BUCKET: logme-static-sites
  #     #   REDIS_URL: redis://host.docker.internal:6379
  #     env_file:
  #       - .env
  #     volumes:
  #       - ./output:/app/output
  #     restart: unless-stopped

  worker:
    <<: *common-service
    command:
      [
        '/bin/sh',
        '-c',
        'npm install -g pnpm && pnpm install --filter=@apps/worker --no-frozen-lockfile && pnpm run dev --filter=@apps/worker',
      ]
    env_file:
      - apps/worker/.env
    # depends_on:
    #   - redis
