services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dev
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    container_name: worker
    env_file:
      - ./apps/worker/.env
    volumes:
      - ./apps/worker:/app
      - ./output:/app/output
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
