services:
  nginx:
    container_name: nginx
    build:
      context: ./apps/nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./apps/nginx/nginx.conf.template.ssl:/etc/nginx/nginx.conf.template.ssl:ro
      - ./apps/nginx/maintenance.html:/usr/share/nginx/html/maintenance.html:ro
      - ./apps/nginx/entrypoint.sh:/entrypoint.sh:ro
      - /home/ubuntu/certs:/etc/nginx/ssl:rw
    networks:
      - app-network
    depends_on:
      - app-${ACTIVE}
    environment:
      - ACTIVE=${ACTIVE}
    env_file:
      - .env
    entrypoint: ['/bin/sh', '/entrypoint.sh']

  vector:
    container_name: vector
    image: timberio/vector:latest-debian
    restart: always
    volumes:
      - ./apps/nginx/vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./apps/nginx/.env
    networks:
      - app-network

  app-green:
    container_name: app-green
    image: kix.ocir.io/axunckhvyv1v/logme-app:green
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - apps/web/.env
    networks:
      - app-network

  app-blue:
    container_name: app-blue
    image: kix.ocir.io/axunckhvyv1v/logme-app:blue
    restart: always
    ports:
      - '3002:3000'
    env_file:
      - ./apps/web/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
