[sources.docker_logs]
type = "docker_logs"
include_containers_glob = ["*nginx*"]

[transforms.parse_json]
type = "remap"
inputs = ["docker_logs"]
source = '''
structured, err = parse_json(.message)
if err != null {
  log("JSON 파싱 실패", level: "warn", error: err)
  structured = {}
}
'''

[sinks.betterstack]
type = "http"
inputs = ["parse_json"]
uri = "https://s1290540.eu-nbg-2.betterstackdata.com"
method = "post"
encoding.codec = "json"
headers.authorization = "Bearer ${BETTER_STACK_SOURCE_TOKEN}"