[sources.nginx]
type = "docker_logs"
include_containers = ["app-nginx-1"]

[transforms.parse_nginx]
type = "remap"
inputs = ["nginx"]
source = '''
structured, err = parse_json(.message)
if err == null {
  . = structured
} else {
  log("Failed to parse JSON", level: "warn")
}
'''

[sinks.betterstack]
type = "http"
inputs = ["parse_nginx"]
method = "post"
uri = "${BETTER_STACK_INGESTING_URL}"
encoding.codec = "json"
headers.authorization = "Bearer ${BETTER_STACK_SOURCE_TOKEN}"

# Enhanced Better Stack sink configuration for completeness and stability
healthcheck.enabled = true

request.headers = { 
  "Content-Type": "application/json",
  "Authorization": "Bearer ${BETTER_STACK_SOURCE_TOKEN}"
}

batch.max_bytes = 1048576  # 1MB
batch.timeout_secs = 5

# Optional: Add retry strategy
retry.max_retries = 5
retry.initial_backoff_secs = 2
retry.max_backoff_secs = 30