export const GITHUB_CLIENT_ID = process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID!
export const GITHUB_REDIRECT_URI = process.env.NEXT_PUBLIC_GITHUB_REDIRECT_URI!
export const NOTION_AUTH_URL = process.env.NEXT_PUBLIC_NOTION_AUTH_URL!