name = "jolly-cloud-80cf"
type = "javascript"
account_id = "3b05ceb0c6ea72be0edfb4a51f240619"
workers_dev = true

compatibility_date = "2025-04-10"

[[r2_buckets]]
binding = "SITE_BUCKET"
bucket_name = "logme"
preview_bucket_name = "logme"


[env.production]
name = "jolly-cloud-80cf-production"

[[env.production.r2_buckets]]
binding = "SITE_BUCKET"
bucket_name = "logme"
preview_bucket_name = "logme"