services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_dev
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
